### ISSUE TITLE
📍Issue: Style Scene 구현

### ISSUE THREAD

**Issue by MinwooJe** [UMC-HowsTheWear/HowsTheWear-iOS#3]
## Description
- Style Scene 구현
- 둘러보기, 이번주 코디, 다음주 코디 미리보기, 작년 이맘때 Scene 모두 포함

## Todo
- [x] 둘러보기 컬렉션 뷰 구현 #2 
- [x] 둘러보기 컬렉션 뷰 셀 구현 #2 
- [x] 이번주/다음주/작년 코디 컬렉션 뷰 구현 #13 
- [x] 이번주/다음주/작년 코디 컬렉션 뷰 셀 구현 #13  
- [x] 상세 페이지 구현 #14
