### ISSUE TITLE
📍Issue: HomeScene 테이블 뷰 셀 구현

### ISSUE THREAD

**Issue by rafa-e1** [UMC-HowsTheWear/HowsTheWear-iOS#6]
## Description
- WeatherScene 테이블 뷰 안에 들어가는 상세 UI 구현

## Todo
- [x] 현재 날씨 상태 아이콘 구현
- [x] 현재 위치 및 온도 구현
- [x] 일간 최저, 최고 기온 및 강수 확률 섹션 구현
- [x] 가로 스크롤로 시간대별 날씨 상태 아이콘 및 온도 섹션 구현
- [x] 주간 날씨 상태 아이콘, 요일, 최저 및 최고 기온 구현
- [x] 오늘의 아이템 구현

## Etc
