### ISSUE TITLE
📍Issue: WeatherScene 테이블 헤더 뷰 구현

### ISSUE THREAD

**Issue by rafa-e1** [UMC-HowsTheWear/HowsTheWear-iOS#7]
## Description
- 현재 날씨 상태 아이콘 및 정보 구현

## Todo
- [ ] 현재 날씨 상태 아이콘 구현
- [ ] 현재 위치 및 온도 스택 뷰로 구현
- [ ] 아래로 스크롤 하면 위치 및 온도가 날씨 아이콘 옆으로 이동하는 애니메이션 + Sticky Header
- [ ] 헤더 뷰가 최상단에 도달했을 때 위치 및 온도가 원래 자리로 이동하는 애니메이션
