### ISSUE TITLE
📍Issue: WeatherScene 바텀 시트 구현

### ISSUE THREAD

**Issue by rafa-e1** [UMC-HowsTheWear/HowsTheWear-iOS#8]
## Description
- 현재 기상 조건에 적합한 옷차림 추천 UI 구현

## Todo
- [ ] 새로운 뷰 컨트롤러 생성
- [ ] 추천 아이템 구현
- [ ] 고정 뷰 생성해서 탭바처럼 작동하도록 구현
## Etc
